### ISSUE TITLE
Run a Powerpoint Karaoke Event

### ISSUE THREAD

**Issue by weswalla** [DWebYVR/notes#37]
Powerpoint Karaoke is basically improvised presentation delivery.

Participants have 5 minutes to deliver a powerpoint presentation with a slide deck they've never seen before.

# todo

- [ ] propose possible dates in late october / november
- [ ] find co-organizers
- [ ] gather set of presentations (probably from the archive.org)

**Comment by weswalla** [comment]
@chickensoupwithrice
@azh

let's make this happen!

**Comment by weswalla** [comment]
Date proposals:
- October 25
- October 26
- November 1
- November 2

**Comment by Chickensoupwithrice** [comment]
Am personally partial to Nov 1 / 2nd. 

We'd also need to schedule a time?

**Comment by azh** [comment]
November 1 works the best for me out of all of these, although if it's after 5pm I could do any of these dates

**Comment by weswalla** [comment]
Okay, I just asked Louisa if any of the above dates work. Will update this issue once I hear back from her!
